n = input("Digite algo coisa: ")
print("O tipo primitivo desse valor é", type(n))
print("É alphanumérico?", n.isalnum())
print("É alfabético?", n.isalpha())
print("É um número?", n.isnumeric())
print("Está em maiúsculas?", n.isupper())
print("É um dígito?", n.isdigit())
print("É um número decimal?", n.isdecimal())
print("É um identificador?", n.isidentifier())
print("Está em minúsculas?", n.islower())
print("Esta vazio?", n.isprintable())
print("Só tem espaços?", n.isspace())
print("Está capitalizada?", n.istitle())
